### ISSUE TITLE
yolox-tiny的freeze_layers~

### ISSUE THREAD

**Issue by liulizi111** [bubbliiiing/yolox-keras#5]
大神，keras和tf版本的yolox-tiny中的freeze_layers没有定义~
在train.py的150行‘freeze_layers = {'s': 125, 'm': 179, 'l': 234, 'x': 290}[phi] ’
谢谢！

**Comment by bubbliiiing** [comment]
马上

**Comment by liulizi111** [comment]
ღ( ´･ᴗ･` )
